# Prometheus Configuration for Scorpius Mempool Elite
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'scorpius-elite'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Service
  - job_name: 'scorpius-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Rule Engine Service (if it exposes metrics)
  - job_name: 'rule-engine'
    static_configs:
      - targets: ['rule-engine:9091']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Notifier Service (if it exposes metrics)
  - job_name: 'notifier'
    static_configs:
      - targets: ['notifier:9092']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Time Machine Service (if it exposes metrics)
  - job_name: 'time-machine'
    static_configs:
      - targets: ['time-machine:9093']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Kafka Exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # ClickHouse metrics (if available)
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']
    scrape_interval: 30s
    metrics_path: '/metrics'
